package bean;
// Generated 12/09/2023 11:25:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ClientesEma generated by hbm2java
 */
@Entity
@Table(name="clientes_ema"
    ,catalog="db_eduardo_aguero"
)
public class ClientesEma  implements java.io.Serializable {


     private int idClienteEma;
     private String nomeCompletoEma;
     private Date dataNascimentoEma;
     private String generoEma;
     private String enderecoEma;
     private String cidadeEma;
     private String cepEma;
     private String telefoneEma;
     private String emailEma;
     private String paisEma;
     private String estadoEma;
     private String cpfEma;
     private String rgEma;
     private String estadoCivilEma;
     private String profissaoEma;
     private Date dataCadastroEma;
     private Set vendasEmas = new HashSet(0);

    public ClientesEma() {
    }

    public ClientesEma(String nomeCompletoEma, Date dataNascimentoEma, String generoEma, String enderecoEma, String cidadeEma, String cepEma, String telefoneEma, String emailEma, String paisEma, String estadoEma, String cpfEma, String rgEma, String estadoCivilEma, String profissaoEma, Date dataCadastroEma, Set vendasEmas) {
       this.nomeCompletoEma = nomeCompletoEma;
       this.dataNascimentoEma = dataNascimentoEma;
       this.generoEma = generoEma;
       this.enderecoEma = enderecoEma;
       this.cidadeEma = cidadeEma;
       this.cepEma = cepEma;
       this.telefoneEma = telefoneEma;
       this.emailEma = emailEma;
       this.paisEma = paisEma;
       this.estadoEma = estadoEma;
       this.cpfEma = cpfEma;
       this.rgEma = rgEma;
       this.estadoCivilEma = estadoCivilEma;
       this.profissaoEma = profissaoEma;
       this.dataCadastroEma = dataCadastroEma;
       this.vendasEmas = vendasEmas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_cliente_ema", unique=true, nullable=false)
    public Integer getIdClienteEma() {
        return this.idClienteEma;
    }
    
    public void setIdClienteEma(Integer idClienteEma) {
        this.idClienteEma = idClienteEma;
    }

    
    @Column(name="nome_completo_ema", length=100)
    public String getNomeCompletoEma() {
        return this.nomeCompletoEma;
    }
    
    public void setNomeCompletoEma(String nomeCompletoEma) {
        this.nomeCompletoEma = nomeCompletoEma;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_nascimento_ema", length=10)
    public Date getDataNascimentoEma() {
        return this.dataNascimentoEma;
    }
    
    public void setDataNascimentoEma(Date dataNascimentoEma) {
        this.dataNascimentoEma = dataNascimentoEma;
    }

    
    @Column(name="genero_ema", length=20)
    public String getGeneroEma() {
        return this.generoEma;
    }
    
    public void setGeneroEma(String generoEma) {
        this.generoEma = generoEma;
    }

    
    @Column(name="endereco_ema")
    public String getEnderecoEma() {
        return this.enderecoEma;
    }
    
    public void setEnderecoEma(String enderecoEma) {
        this.enderecoEma = enderecoEma;
    }

    
    @Column(name="cidade_ema", length=100)
    public String getCidadeEma() {
        return this.cidadeEma;
    }
    
    public void setCidadeEma(String cidadeEma) {
        this.cidadeEma = cidadeEma;
    }

    
    @Column(name="cep_ema", length=10)
    public String getCepEma() {
        return this.cepEma;
    }
    
    public void setCepEma(String cepEma) {
        this.cepEma = cepEma;
    }

    
    @Column(name="telefone_ema", length=20)
    public String getTelefoneEma() {
        return this.telefoneEma;
    }
    
    public void setTelefoneEma(String telefoneEma) {
        this.telefoneEma = telefoneEma;
    }

    
    @Column(name="email_ema")
    public String getEmailEma() {
        return this.emailEma;
    }
    
    public void setEmailEma(String emailEma) {
        this.emailEma = emailEma;
    }

    
    @Column(name="pais_ema", length=50)
    public String getPaisEma() {
        return this.paisEma;
    }
    
    public void setPaisEma(String paisEma) {
        this.paisEma = paisEma;
    }

    
    @Column(name="estado_ema", length=50)
    public String getEstadoEma() {
        return this.estadoEma;
    }
    
    public void setEstadoEma(String estadoEma) {
        this.estadoEma = estadoEma;
    }

    
    @Column(name="cpf_ema", length=20)
    public String getCpfEma() {
        return this.cpfEma;
    }
    
    public void setCpfEma(String cpfEma) {
        this.cpfEma = cpfEma;
    }

    
    @Column(name="rg_ema", length=20)
    public String getRgEma() {
        return this.rgEma;
    }
    
    public void setRgEma(String rgEma) {
        this.rgEma = rgEma;
    }

    
    @Column(name="estado_civil_ema", length=50)
    public String getEstadoCivilEma() {
        return this.estadoCivilEma;
    }
    
    public void setEstadoCivilEma(String estadoCivilEma) {
        this.estadoCivilEma = estadoCivilEma;
    }

    
    @Column(name="profissao_ema", length=100)
    public String getProfissaoEma() {
        return this.profissaoEma;
    }
    
    public void setProfissaoEma(String profissaoEma) {
        this.profissaoEma = profissaoEma;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_cadastro_ema", length=10)
    public Date getDataCadastroEma() {
        return this.dataCadastroEma;
    }
    
    public void setDataCadastroEma(Date dataCadastroEma) {
        this.dataCadastroEma = dataCadastroEma;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clientesEma")
    public Set getVendasEmas() {
        return this.vendasEmas;
    }
    
    public void setVendasEmas(Set vendasEmas) {
        this.vendasEmas = vendasEmas;
    }




}


