package bean;
// Generated 12/09/2023 11:25:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendasProdutosEma generated by hbm2java
 */
@Entity
@Table(name="vendas_produtos_ema"
    ,catalog="db_eduardo_aguero"
)
public class VendasProdutosEma  implements java.io.Serializable {


     private Integer idVendaProdutoEma;
     private ProdutosEma produtosEma;
     private VendasEma vendasEma;
     private Integer quantidadeVendidaEma;
     private BigDecimal precoUnitarioEma;

    public VendasProdutosEma() {
    }

    public VendasProdutosEma(ProdutosEma produtosEma, VendasEma vendasEma, Integer quantidadeVendidaEma, BigDecimal precoUnitarioEma) {
       this.produtosEma = produtosEma;
       this.vendasEma = vendasEma;
       this.quantidadeVendidaEma = quantidadeVendidaEma;
       this.precoUnitarioEma = precoUnitarioEma;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_venda_produto_ema", unique=true, nullable=false)
    public Integer getIdVendaProdutoEma() {
        return this.idVendaProdutoEma;
    }
    
    public void setIdVendaProdutoEma(Integer idVendaProdutoEma) {
        this.idVendaProdutoEma = idVendaProdutoEma;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_produto_ema")
    public ProdutosEma getProdutosEma() {
        return this.produtosEma;
    }
    
    public void setProdutosEma(ProdutosEma produtosEma) {
        this.produtosEma = produtosEma;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_venda_ema")
    public VendasEma getVendasEma() {
        return this.vendasEma;
    }
    
    public void setVendasEma(VendasEma vendasEma) {
        this.vendasEma = vendasEma;
    }

    
    @Column(name="quantidade_vendida_ema")
    public Integer getQuantidadeVendidaEma() {
        return this.quantidadeVendidaEma;
    }
    
    public void setQuantidadeVendidaEma(Integer quantidadeVendidaEma) {
        this.quantidadeVendidaEma = quantidadeVendidaEma;
    }

    
    @Column(name="preco_unitario_ema", precision=10)
    public BigDecimal getPrecoUnitarioEma() {
        return this.precoUnitarioEma;
    }
    
    public void setPrecoUnitarioEma(BigDecimal precoUnitarioEma) {
        this.precoUnitarioEma = precoUnitarioEma;
    }




}


