package bean;
// Generated 12/09/2023 11:25:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendasEma generated by hbm2java
 */
@Entity
@Table(name="vendas_ema"
    ,catalog="db_eduardo_aguero"
)
public class VendasEma  implements java.io.Serializable {


     private Integer idVendaEma;
     private ClientesEma clientesEma;
     private FuncionariosEma funcionariosEma;
     private Date dataVendaEma;
     private BigDecimal totalVendaEma;
     private String metodoPagamentoEma;
     private BigDecimal descontoEma;
     private String statusEntregaEma;
     private Set vendasProdutosEmas = new HashSet(0);

    public VendasEma() {
    }

    public VendasEma(ClientesEma clientesEma, FuncionariosEma funcionariosEma, Date dataVendaEma, BigDecimal totalVendaEma, String metodoPagamentoEma, BigDecimal descontoEma, String statusEntregaEma, Set vendasProdutosEmas) {
       this.clientesEma = clientesEma;
       this.funcionariosEma = funcionariosEma;
       this.dataVendaEma = dataVendaEma;
       this.totalVendaEma = totalVendaEma;
       this.metodoPagamentoEma = metodoPagamentoEma;
       this.descontoEma = descontoEma;
       this.statusEntregaEma = statusEntregaEma;
       this.vendasProdutosEmas = vendasProdutosEmas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_venda_ema", unique=true, nullable=false)
    public Integer getIdVendaEma() {
        return this.idVendaEma;
    }
    
    public void setIdVendaEma(Integer idVendaEma) {
        this.idVendaEma = idVendaEma;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_cliente_ema")
    public ClientesEma getClientesEma() {
        return this.clientesEma;
    }
    
    public void setClientesEma(ClientesEma clientesEma) {
        this.clientesEma = clientesEma;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_funcionario_ema")
    public FuncionariosEma getFuncionariosEma() {
        return this.funcionariosEma;
    }
    
    public void setFuncionariosEma(FuncionariosEma funcionariosEma) {
        this.funcionariosEma = funcionariosEma;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_venda_ema", length=10)
    public Date getDataVendaEma() {
        return this.dataVendaEma;
    }
    
    public void setDataVendaEma(Date dataVendaEma) {
        this.dataVendaEma = dataVendaEma;
    }

    
    @Column(name="total_venda_ema", precision=10)
    public BigDecimal getTotalVendaEma() {
        return this.totalVendaEma;
    }
    
    public void setTotalVendaEma(BigDecimal totalVendaEma) {
        this.totalVendaEma = totalVendaEma;
    }

    
    @Column(name="metodo_pagamento_ema", length=50)
    public String getMetodoPagamentoEma() {
        return this.metodoPagamentoEma;
    }
    
    public void setMetodoPagamentoEma(String metodoPagamentoEma) {
        this.metodoPagamentoEma = metodoPagamentoEma;
    }

    
    @Column(name="desconto_ema", precision=5)
    public BigDecimal getDescontoEma() {
        return this.descontoEma;
    }
    
    public void setDescontoEma(BigDecimal descontoEma) {
        this.descontoEma = descontoEma;
    }

    
    @Column(name="status_entrega_ema", length=50)
    public String getStatusEntregaEma() {
        return this.statusEntregaEma;
    }
    
    public void setStatusEntregaEma(String statusEntregaEma) {
        this.statusEntregaEma = statusEntregaEma;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vendasEma")
    public Set getVendasProdutosEmas() {
        return this.vendasProdutosEmas;
    }
    
    public void setVendasProdutosEmas(Set vendasProdutosEmas) {
        this.vendasProdutosEmas = vendasProdutosEmas;
    }




}


